### ISSUE TITLE
hsignal-0.2.7.1 ships broken Setup.lhs file

### ISSUE THREAD

**Issue by peti** [amcphail/hsignal#1]
Citing from http://hydra.cryp.to/build/1343750/log/raw:

```
Setup.lhs:8:10:
    Could not find module ‘Config’
    It is a member of the hidden package ‘ghc-7.10.2’.
    Use -v to see a list of the files searched for.
```

**Comment by peti** [comment]
Related to https://github.com/fpco/stackage/issues/903.

**Comment by amcphail** [comment]
hsignal-0.2.7.4 should work:  https://github.com/amcphail/hsignal/commit/da065a0db6df8b127143fbc594628083d013b89c
